// Generated by gencpp from file image_processing_pkg/StateChangeRequestFeedback.msg
// DO NOT EDIT!


#ifndef IMAGE_PROCESSING_PKG_MESSAGE_STATECHANGEREQUESTFEEDBACK_H
#define IMAGE_PROCESSING_PKG_MESSAGE_STATECHANGEREQUESTFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace image_processing_pkg
{
template <class ContainerAllocator>
struct StateChangeRequestFeedback_
{
  typedef StateChangeRequestFeedback_<ContainerAllocator> Type;

  StateChangeRequestFeedback_()
    : status(false)  {
    }
  StateChangeRequestFeedback_(const ContainerAllocator& _alloc)
    : status(false)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::image_processing_pkg::StateChangeRequestFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::image_processing_pkg::StateChangeRequestFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct StateChangeRequestFeedback_

typedef ::image_processing_pkg::StateChangeRequestFeedback_<std::allocator<void> > StateChangeRequestFeedback;

typedef boost::shared_ptr< ::image_processing_pkg::StateChangeRequestFeedback > StateChangeRequestFeedbackPtr;
typedef boost::shared_ptr< ::image_processing_pkg::StateChangeRequestFeedback const> StateChangeRequestFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::image_processing_pkg::StateChangeRequestFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::image_processing_pkg::StateChangeRequestFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace image_processing_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'image_processing_pkg': ['/home/odroid/artbot_ws/src/image_processing_pkg/msg', '/home/odroid/artbot_ws/devel/share/image_processing_pkg/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::image_processing_pkg::StateChangeRequestFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::image_processing_pkg::StateChangeRequestFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::image_processing_pkg::StateChangeRequestFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::image_processing_pkg::StateChangeRequestFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::image_processing_pkg::StateChangeRequestFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::image_processing_pkg::StateChangeRequestFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::image_processing_pkg::StateChangeRequestFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a1255d4d998bd4d6585c64639b5ee9a";
  }

  static const char* value(const ::image_processing_pkg::StateChangeRequestFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a1255d4d998bd4dULL;
  static const uint64_t static_value2 = 0x6585c64639b5ee9aULL;
};

template<class ContainerAllocator>
struct DataType< ::image_processing_pkg::StateChangeRequestFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "image_processing_pkg/StateChangeRequestFeedback";
  }

  static const char* value(const ::image_processing_pkg::StateChangeRequestFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::image_processing_pkg::StateChangeRequestFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#feedback\n\
bool status\n\
";
  }

  static const char* value(const ::image_processing_pkg::StateChangeRequestFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::image_processing_pkg::StateChangeRequestFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StateChangeRequestFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::image_processing_pkg::StateChangeRequestFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::image_processing_pkg::StateChangeRequestFeedback_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMAGE_PROCESSING_PKG_MESSAGE_STATECHANGEREQUESTFEEDBACK_H
