(cl:defpackage image_processing_pkg-msg
  (:use )
  (:export
   "<PROCESSEDIMAGE>"
   "PROCESSEDIMAGE"
   "<STATECHANGEREQUESTACTION>"
   "STATECHANGEREQUESTACTION"
   "<STATECHANGEREQUESTACTIONFEEDBACK>"
   "STATECHANGEREQUESTACTIONFEEDBACK"
   "<STATECHANGEREQUESTACTIONGOAL>"
   "STATECHANGEREQUESTACTIONGOAL"
   "<STATECHANGEREQUESTACTIONRESULT>"
   "STATECHANGEREQUESTACTIONRESULT"
   "<STATECHANGEREQUESTFEEDBACK>"
   "STATECHANGEREQUESTFEEDBACK"
   "<STATECHANGEREQUESTGOAL>"
   "STATECHANGEREQUESTGOAL"
   "<STATECHANGEREQUESTRESULT>"
   "STATECHANGEREQUESTRESULT"
  ))

