(cl:defpackage image_processing_pkg-msg
  (:use )
  (:export
   "<PROCESSEDIMAGE>"
   "PROCESSEDIMAGE"
   "<TAKE_SELFIEACTION>"
   "TAKE_SELFIEACTION"
   "<TAKE_SELFIEACTIONFEEDBACK>"
   "TAKE_SELFIEACTIONFEEDBACK"
   "<TAKE_SELFIEACTIONGOAL>"
   "TAKE_SELFIEACTIONGOAL"
   "<TAKE_SELFIEACTIONRESULT>"
   "TAKE_SELFIEACTIONRESULT"
   "<TAKE_SELFIEFEEDBACK>"
   "TAKE_SELFIEFEEDBACK"
   "<TAKE_SELFIEGOAL>"
   "TAKE_SELFIEGOAL"
   "<TAKE_SELFIERESULT>"
   "TAKE_SELFIERESULT"
  ))

