; Auto-generated. Do not edit!


(cl:in-package image_processing_pkg-msg)


;//! \htmlinclude StateChangeRequestFeedback.msg.html

(cl:defclass <StateChangeRequestFeedback> (roslisp-msg-protocol:ros-message)
  ((status
    :reader status
    :initarg :status
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass StateChangeRequestFeedback (<StateChangeRequestFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <StateChangeRequestFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'StateChangeRequestFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name image_processing_pkg-msg:<StateChangeRequestFeedback> is deprecated: use image_processing_pkg-msg:StateChangeRequestFeedback instead.")))

(cl:ensure-generic-function 'status-val :lambda-list '(m))
(cl:defmethod status-val ((m <StateChangeRequestFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader image_processing_pkg-msg:status-val is deprecated.  Use image_processing_pkg-msg:status instead.")
  (status m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <StateChangeRequestFeedback>) ostream)
  "Serializes a message object of type '<StateChangeRequestFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'status) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <StateChangeRequestFeedback>) istream)
  "Deserializes a message object of type '<StateChangeRequestFeedback>"
    (cl:setf (cl:slot-value msg 'status) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<StateChangeRequestFeedback>)))
  "Returns string type for a message object of type '<StateChangeRequestFeedback>"
  "image_processing_pkg/StateChangeRequestFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'StateChangeRequestFeedback)))
  "Returns string type for a message object of type 'StateChangeRequestFeedback"
  "image_processing_pkg/StateChangeRequestFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<StateChangeRequestFeedback>)))
  "Returns md5sum for a message object of type '<StateChangeRequestFeedback>"
  "3a1255d4d998bd4d6585c64639b5ee9a")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'StateChangeRequestFeedback)))
  "Returns md5sum for a message object of type 'StateChangeRequestFeedback"
  "3a1255d4d998bd4d6585c64639b5ee9a")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<StateChangeRequestFeedback>)))
  "Returns full string definition for message of type '<StateChangeRequestFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%bool status~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'StateChangeRequestFeedback)))
  "Returns full string definition for message of type 'StateChangeRequestFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%bool status~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <StateChangeRequestFeedback>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <StateChangeRequestFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'StateChangeRequestFeedback
    (cl:cons ':status (status msg))
))
